export const projectData = [
  {
    title: "Pro Manage",
    alt: "Pro Manage Image",
    skills: "React Js, Express js, Node js , MongoDB",
    description: "This is a full stack application like jira to manage the task and analytics of task. As admin after login we can create task , assign the user which is added in the board and share the link with anyone they can see the progress of task using that link. Creation of task is only available to authorised user only.",
    img: "/projects/promanage.png",
    link: "https://pro-manage-g07c.onrender.com",
    repo: "https://github.com/NikhilRaj060/Pro-Manage",
    id: 0,
  },
  {
    title: "Quizzie",
    alt: "Quizzie Image",
    skills: "React Js, Express js, Node js , MongoDB",
    description: "This is a full stack application for creating and playing Quiz. As admin after login you can create quiz and share the link with anyone they can play using that link.  Creation is only available to authorised user only.",
    img: "/projects/quizzie.png",
    link: "https://quizzie-9k6u.onrender.com",
    repo: "https://github.com/NikhilRaj060/Quizzie",
    id: 1,
  },
  {
    title: "Sait Feedback",
    alt: "Sait Feedback Image",
    skills: "MERN Stack, Firebase",
    description: "This is a full stack feedback application for Sambhram Institution. This app is the frontend of the whole feedback system. Admin section is only available to authorised department head only. Only Sambhram's Student can use this app.",
    img: "/projects/sait-feedback.png",
    link: "https://saitfeedback.netlify.app",
    repo: "https://github.com/NikhilRaj060/College-Feedback-System",
    id: 2,
  },
  {
    title: "Quora Clone App",
    alt: "Quora Clone Image",
    skills: "Mern Stack",
    description: "",
    img: "/projects/quora-clone.png",
    link: "https://nikhilraj060.github.io/quora-clone/",
    repo: "https://github.com/NikhilRaj060/quora-clone",
    id: 3,
  },
  {
    title: "Rock Paper Scissor Game",
    alt: "Rock Paper Scissor Image",
    skills: "HTML, CSS, JS",
    description: "",
    img: "/projects/rockpaperscessior.png",
    link: "https://cuvette-rock-paper-scissor-game.netlify.app",
    repo: "https://github.com/NikhilRaj060/Rock-Paper-Scissor",
    id: 4,
  },
  {
    title: "Pocket Notes App",
    alt: "Pocket Notes Image",
    skills: "MERN Stack, Tailwind",
    description: "",
    img: "/projects/pocket_notes.avif",
    link: "https://pocketfriendly-notes.netlify.app",
    repo: "https://github.com/NikhilRaj060/Pocket-Notes",
    id: 5,
  },
  {
    title: "Daprr Landing Page",
    alt: "Daprr Landing Image",
    skills: "HTML, CSS, JS",
    description: "",
    img: "/projects/dappr-landing-page.png",
    link: "https://daprr-landing-cuvette.netlify.app",
    repo: "https://github.com/NikhilRaj060/Dappr_Landing_Page",
    id: 6,
  },
];

export const skillData = [
  {
    title: "FrontEnd",
    skills: [
      "React Js",
      "Angular",
      "HTML",
      "CSS",
      "Material Ui",
      "TypeScript",
      "Tailwind",
    ],
  },
  {
    title: "BackEnd",
    skills: ["Node Js", "Express Js", "Rest API", "Spring Boot"],
  },
  {
    title: "Database",
    skills: ["MongoDB", "Postgres", "Firebase"],
  },
  {
    title: "Programming",
    skills: ["Java", "C", ,"JavaScript"],
  },
  {
    title: "Tools & Libraries",
    skills: [
      "Git",
      "GitHub",
      "Bitbucket",
      "Jira",
      "Confluence",
      "JWT",
      "Framer Motion",
      "Figma",
      "Postman",
    ],
  },
];
